// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Datakit")]
[assembly: AssemblyDescriptionAttribute("C# Datakit Bindings")]
[assembly: GuidAttribute("58F47959-A6E8-4433-A94A-61DBCC01A1E8")]
[assembly: AssemblyCompanyAttribute("Docker")]
[assembly: AssemblyCopyrightAttribute("Copyright © Docker, Inc. 2016")]
[assembly: AssemblyVersionAttribute("0.1.0.9999")]
[assembly: AssemblyFileVersionAttribute("0.1.0.9999")]
[assembly: AssemblyMetadataAttribute("githash","79659e")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.0.9999";
        internal const string InformationalVersion = "0.1.0.9999";
    }
}
